// Code generated by mockery. DO NOT EDIT.

package auth

import (
	auth "github.com/goravel/framework/contracts/auth"
	mock "github.com/stretchr/testify/mock"
)

// Auth is an autogenerated mock type for the Auth type
type Auth struct {
	mock.Mock
}

type Auth_Expecter struct {
	mock *mock.Mock
}

func (_m *Auth) EXPECT() *Auth_Expecter {
	return &Auth_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields:
func (_m *Auth) Check() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Auth_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type Auth_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
func (_e *Auth_Expecter) Check() *Auth_Check_Call {
	return &Auth_Check_Call{Call: _e.mock.On("Check")}
}

func (_c *Auth_Check_Call) Run(run func()) *Auth_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Auth_Check_Call) Return(_a0 bool) *Auth_Check_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Auth_Check_Call) RunAndReturn(run func() bool) *Auth_Check_Call {
	_c.Call.Return(run)
	return _c
}

// GetDefaultDriver provides a mock function with given fields:
func (_m *Auth) GetDefaultDriver() auth.Guard {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDefaultDriver")
	}

	var r0 auth.Guard
	if rf, ok := ret.Get(0).(func() auth.Guard); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.Guard)
		}
	}

	return r0
}

// Auth_GetDefaultDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDefaultDriver'
type Auth_GetDefaultDriver_Call struct {
	*mock.Call
}

// GetDefaultDriver is a helper method to define mock.On call
func (_e *Auth_Expecter) GetDefaultDriver() *Auth_GetDefaultDriver_Call {
	return &Auth_GetDefaultDriver_Call{Call: _e.mock.On("GetDefaultDriver")}
}

func (_c *Auth_GetDefaultDriver_Call) Run(run func()) *Auth_GetDefaultDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Auth_GetDefaultDriver_Call) Return(_a0 auth.Guard) *Auth_GetDefaultDriver_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Auth_GetDefaultDriver_Call) RunAndReturn(run func() auth.Guard) *Auth_GetDefaultDriver_Call {
	_c.Call.Return(run)
	return _c
}

// Guard provides a mock function with given fields: guard
func (_m *Auth) Guard(guard string) auth.Guard {
	ret := _m.Called(guard)

	if len(ret) == 0 {
		panic("no return value specified for Guard")
	}

	var r0 auth.Guard
	if rf, ok := ret.Get(0).(func(string) auth.Guard); ok {
		r0 = rf(guard)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.Guard)
		}
	}

	return r0
}

// Auth_Guard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Guard'
type Auth_Guard_Call struct {
	*mock.Call
}

// Guard is a helper method to define mock.On call
//   - guard string
func (_e *Auth_Expecter) Guard(guard interface{}) *Auth_Guard_Call {
	return &Auth_Guard_Call{Call: _e.mock.On("Guard", guard)}
}

func (_c *Auth_Guard_Call) Run(run func(guard string)) *Auth_Guard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Auth_Guard_Call) Return(_a0 auth.Guard) *Auth_Guard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Auth_Guard_Call) RunAndReturn(run func(string) auth.Guard) *Auth_Guard_Call {
	_c.Call.Return(run)
	return _c
}

// Id provides a mock function with given fields:
func (_m *Auth) Id() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Id")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Auth_Id_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Id'
type Auth_Id_Call struct {
	*mock.Call
}

// Id is a helper method to define mock.On call
func (_e *Auth_Expecter) Id() *Auth_Id_Call {
	return &Auth_Id_Call{Call: _e.mock.On("Id")}
}

func (_c *Auth_Id_Call) Run(run func()) *Auth_Id_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Auth_Id_Call) Return(_a0 string, _a1 error) *Auth_Id_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Auth_Id_Call) RunAndReturn(run func() (string, error)) *Auth_Id_Call {
	_c.Call.Return(run)
	return _c
}

// User provides a mock function with given fields:
func (_m *Auth) User() *any {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for User")
	}

	var r0 *any
	if rf, ok := ret.Get(0).(func() *any); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*any)
		}
	}

	return r0
}

// Auth_User_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'User'
type Auth_User_Call struct {
	*mock.Call
}

// User is a helper method to define mock.On call
func (_e *Auth_Expecter) User() *Auth_User_Call {
	return &Auth_User_Call{Call: _e.mock.On("User")}
}

func (_c *Auth_User_Call) Run(run func()) *Auth_User_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Auth_User_Call) Return(_a0 *any) *Auth_User_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Auth_User_Call) RunAndReturn(run func() *any) *Auth_User_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuth creates a new instance of Auth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *Auth {
	mock := &Auth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
